blank_issues_enabled: true
contact_links:
  - name: 🤔 Ask a question（提问和讨论）
    url: https://github.com/zhensherlock/webrtc-streamer-helper/discussions
    about: Ask questions and discuss with other community members
